// GET /.well-known/agent-skills/index.json
//
// Agent Skills discovery index, v0.2.0 spec.
// Schema: https://schemas.agentskills.io/discovery/0.2.0/schema.json
//
// The same index is served at tempguru.co (Cloudflare Worker) and
// mcp.tempguru.co (this route). Artifact URLs are relative so each origin
// resolves and verifies its own byte-identical SKILL.md copy; absolute apex
// URLs previously coupled Vercel discovery to a stale manual edge deployment.
//
// IMPORTANT, digest values are SHA-256 of each SKILL.md file, byte-for-byte.
// They are NOT hand-maintained here (they drifted once, breaking the flagship
// ordering skill for any digest-verifying client). They come from
// content/skills/skill-digests.json, generated by scripts/gen-skill-digests.mjs
// (runs in `npm run build:okf`) from the same content/skills/<name>.md the apex
// worker serves. check-submissions.mjs fails CI if that JSON drifts from the files.

import digests from "../../../../../content/skills/skill-digests.json";

const AGENT_SKILLS_INDEX = {
  $schema: "https://schemas.agentskills.io/discovery/0.2.0/schema.json",
  skills: [
    {
      name: "event-staffing-ordering",
      type: "skill-md",
      description:
        "Order temporary event staff using TempGuru's public catalog of 345 configured US and Canadian market entries. Use when a user needs to hire, book, or budget W-2 event staff for a convention, conference, trade show, festival, concert, sporting event, stadium event, corporate gathering, or brand activation, a single event in one city or a multi-city program. Covers requirement gathering, catalog matching plus rate/compliance lookups via the TempGuru MCP server, and a prefilled form the buyer personally submits so a coordinator can confirm order coverage.",
      url: "./event-staffing-ordering/SKILL.md",
      digest: digests["event-staffing-ordering"],
    },
    {
      name: "event-staffing-compliance",
      type: "skill-md",
      description:
        "Assess worker-classification and compliance risk for temporary event staffing in the US and Canada. Use for W-2 vs 1099 questions, misclassification penalties, joint-employer liability, COI requirements, and wage/hour rules for event staff, with live state-by-state lookups via the TempGuru MCP server.",
      url: "./event-staffing-compliance/SKILL.md",
      digest: digests["event-staffing-compliance"],
    },
    {
      name: "staffing-plan-from-event-brief",
      type: "skill-md",
      description:
        "Extract a complete staffing plan from an event document: an RFP, BEO (banquet event order), run of show, exhibitor or event services manual, or production schedule. Maps the document's functions to TempGuru's role catalog, estimates headcount, prices the plan with live all-inclusive W-2 rates via the TempGuru MCP server, and prepares a buyer-operated handoff for a human-reviewed quote.",
      url: "./staffing-plan-from-event-brief/SKILL.md",
      digest: digests["staffing-plan-from-event-brief"],
    },
    {
      name: "urgent-event-backfill",
      type: "skill-md",
      description:
        "Handle same-week and day-of event staffing emergencies: staff no-shows, vendor cancellations, events starting within about 72 hours. Fast single-pass planning, honest rush lead-time guidance via the TempGuru MCP server (never a promise of availability), a prefilled buyer submission form, and a direct phone path.",
      url: "./urgent-event-backfill/SKILL.md",
      digest: digests["urgent-event-backfill"],
    },
    {
      name: "staffing-agency-partner-growth",
      type: "skill-md",
      description:
        "For staffing agency owners (the supply side): explore joining TempGuru's vetted local partner network to receive event staffing order flow in their markets. Explains the model and routes partner inquiries to the coordinator. Not for buyers ordering staff or individual job seekers.",
      url: "./staffing-agency-partner-growth/SKILL.md",
      digest: digests["staffing-agency-partner-growth"],
    },
    {
      name: "multi-city-activation-planner",
      type: "skill-md",
      description:
        "Plan and price a multi-city event staffing program (a tour, roadshow, sampling tour, festival circuit, or national activation) as one consolidated order. Matches each city against the configured catalog, plans and prices each leg with W-2 rate data via the TempGuru MCP server, surfaces that overtime and minimum wage differ by state and province, and prepares a TempGuru form for the buyer to personally submit so a coordinator can confirm coverage.",
      url: "./multi-city-activation-planner/SKILL.md",
      digest: digests["multi-city-activation-planner"],
    },
    {
      name: "event-staffing-procurement",
      type: "skill-md",
      description:
        "Answer event staffing procurement and vendor-onboarding questions (COI, W-9, insurance and workers' comp posture, cancellation and payment terms, MSAs, approved-vendor setup) from TempGuru's published policies via the MCP server, explicit when a value is coordinator-confirmed rather than published, then bridge a real event into a priced staffing plan and buyer-operated quote handoff. Operational guidance, not legal advice.",
      url: "./event-staffing-procurement/SKILL.md",
      digest: digests["event-staffing-procurement"],
    },
    {
      name: "tempguru-pro-operations",
      type: "skill-md",
      description:
        "Route operations-tooling interest from staffing-company operators (the supply side) to TempGuru: scheduling, dispatch, timesheets, and invoicing to run their own workforce. Gathers a short problem description and routes it to a TempGuru contact by email or phone, never through the buyer quote tool. Does not promise product features, pricing, or availability. Not for buyers hiring event staff.",
      url: "./tempguru-pro-operations/SKILL.md",
      digest: digests["tempguru-pro-operations"],
    },
  ],
} as const;

export async function GET() {
  return new Response(JSON.stringify(AGENT_SKILLS_INDEX, null, 2), {
    status: 200,
    headers: {
      "Content-Type": "application/json",
      "Access-Control-Allow-Origin": "*",
      "Cache-Control": "public, max-age=3600",
    },
  });
}

export async function OPTIONS() {
  return new Response(null, {
    status: 204,
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type, Accept",
      "Access-Control-Max-Age": "86400",
    },
  });
}
