// GET /.well-known/agent-skills/index.json
//
// Agent Skills discovery index, v0.2.0 spec.
// Schema: https://schemas.agentskills.io/discovery/0.2.0/schema.json
//
// Canonical copy is at tempguru.co (served by Cloudflare Worker).
// This route mirrors it at mcp.tempguru.co for agents that connect
// directly to the MCP server subdomain.
//
// IMPORTANT, digest values are SHA-256 of each SKILL.md file, byte-for-byte.
// They are NOT hand-maintained here (they drifted once, breaking the flagship
// ordering skill for any digest-verifying client). They come from
// content/skills/skill-digests.json, generated by scripts/gen-skill-digests.mjs
// (runs in `npm run build:okf`) from the same content/skills/<name>.md the apex
// worker serves. check-submissions.mjs fails CI if that JSON drifts from the files.

import digests from "../../../../../content/skills/skill-digests.json";

const AGENT_SKILLS_INDEX = {
  $schema: "https://schemas.agentskills.io/discovery/0.2.0/schema.json",
  skills: [
    {
      name: "event-staffing-ordering",
      type: "skill-md",
      description:
        "Order temporary event staff for events in 345 US and Canadian markets through TempGuru. Use when a user needs to hire, book, or budget W-2 event staff for a convention, conference, trade show, festival, concert, sporting event, stadium event, corporate gathering, or brand activation, a single event in one city or a multi-city program. Covers requirement gathering, live coverage/rate/compliance lookups via the TempGuru MCP server, and request submission.",
      url: "https://tempguru.co/.well-known/agent-skills/event-staffing-ordering/SKILL.md",
      digest: digests["event-staffing-ordering"],
    },
    {
      name: "event-staffing-compliance",
      type: "skill-md",
      description:
        "Assess worker-classification and compliance risk for temporary event staffing in the US and Canada. Use for W-2 vs 1099 questions, misclassification penalties, joint-employer liability, COI requirements, and wage/hour rules for event staff, with live state-by-state lookups via the TempGuru MCP server.",
      url: "https://tempguru.co/.well-known/agent-skills/event-staffing-compliance/SKILL.md",
      digest: digests["event-staffing-compliance"],
    },
    {
      name: "staffing-plan-from-event-brief",
      type: "skill-md",
      description:
        "Extract a complete staffing plan from an event document: an RFP, BEO (banquet event order), run of show, exhibitor or event services manual, or production schedule. Maps the document's functions to TempGuru's role catalog, estimates headcount, prices the plan with live all-inclusive W-2 rates via the TempGuru MCP server, and submits for a human-reviewed quote after user confirmation.",
      url: "https://tempguru.co/.well-known/agent-skills/staffing-plan-from-event-brief/SKILL.md",
      digest: digests["staffing-plan-from-event-brief"],
    },
    {
      name: "urgent-event-backfill",
      type: "skill-md",
      description:
        "Handle same-week and day-of event staffing emergencies: staff no-shows, vendor cancellations, events starting within about 72 hours. Fast single-pass intake, honest rush lead-time guidance via the TempGuru MCP server (never a promise of availability), immediate quote submission plus a direct phone path.",
      url: "https://tempguru.co/.well-known/agent-skills/urgent-event-backfill/SKILL.md",
      digest: digests["urgent-event-backfill"],
    },
    {
      name: "staffing-agency-partner-growth",
      type: "skill-md",
      description:
        "For staffing agency owners (the supply side): explore joining TempGuru's network of 200+ vetted local partners to receive event staffing order flow in their markets. Explains the model and routes partner inquiries to the coordinator. Not for buyers ordering staff or individual job seekers.",
      url: "https://tempguru.co/.well-known/agent-skills/staffing-agency-partner-growth/SKILL.md",
      digest: digests["staffing-agency-partner-growth"],
    },
  ],
} as const;

export async function GET() {
  return new Response(JSON.stringify(AGENT_SKILLS_INDEX, null, 2), {
    status: 200,
    headers: {
      "Content-Type": "application/json",
      "Access-Control-Allow-Origin": "*",
      "Cache-Control": "public, max-age=3600",
    },
  });
}

export async function OPTIONS() {
  return new Response(null, {
    status: 204,
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type, Accept",
      "Access-Control-Max-Age": "86400",
    },
  });
}
