// Generates the TempGuru Open Knowledge Format (OKF v0.1) bundle in public/okf/
// from the canonical data in content/mcp-data/ (+ prose facts embedded below),
// plus a public/llms.txt pointer so the bundle is discoverable.
//
// OKF is Google Cloud's vendor-neutral knowledge interchange format: a directory
// of plain Markdown files with YAML frontmatter that link to one another. One
// file = one concept. The only required frontmatter field is `type`. Spec:
// https://github.com/GoogleCloudPlatform/knowledge-catalog/blob/main/okf/SPEC.md
//
// Conformance rules this generator honors:
//   §3.1  index.md / log.md are reserved, never used for concept documents.
//   §6    index files carry NO frontmatter (body = sections + grouped links).
//   §7    log.md carries NO frontmatter (date-grouped prose, newest first).
//   §11   the bundle-root index.md is the ONLY index that may carry frontmatter,
//         and only to declare okf_version.
//   §4.1  every concept file has a required `type`.
//
// Run from anywhere:  node scripts/build-okf.mjs   (or: npm run build:okf)
// Served at:          https://mcp.tempguru.co/okf/  (and git-cloneable in-repo)
//
// SOURCE-OF-TRUTH RULE: never hand-edit anything under public/okf/. Edit
// content/mcp-data/ (data) or this script (prose/structure) and regenerate.
// The Rate Index figures here are computed with the SAME logic as the live
// get_rate_benchmark MCP tool (src/lib/mcp/city-rates.ts) so the bundle and the
// API cannot drift.

import { readFileSync, writeFileSync, mkdirSync, rmSync, readdirSync } from "node:fs";
import { execSync } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..");
const dataDir = join(repoRoot, "content", "mcp-data");
const publicDir = join(repoRoot, "public");
const outDir = join(publicDir, "okf");

const load = (f) => JSON.parse(readFileSync(join(dataDir, f), "utf8"));
const cities = load("cities.json");
const roles = load("roles.json");
const pricing = load("role-pricing.json");
const compliance = load("state-compliance.json");
const cityRates = load("city-rates.json");

// ── reference docs DERIVED from source so they cannot drift ──────────────────
// REST surface from the dumped OpenAPI spec (scripts/dump-openapi.mjs); MCP tools
// from the registry definitions; workflow prose from the real agent skills.
let openapi = null;
try { openapi = JSON.parse(readFileSync(join(dataDir, "openapi.json"), "utf8")); } catch { /* run scripts/dump-openapi.mjs first */ }

const API_OPS = openapi
  ? Object.entries(openapi.paths).flatMap(([p, item]) =>
      ["get", "post", "put", "patch", "delete"].filter((m) => item[m]).map((m) => ({
        method: m.toUpperCase(),
        path: p,
        summary: (item[m].summary || item[m].operationId || "").trim(),
      })))
  : readdirSync(join(repoRoot, "src", "app", "api", "v1"), { withFileTypes: true })
      .filter((d) => d.isDirectory() && d.name !== "health").sort()
      .map((d) => ({ method: "GET", path: `/api/v1/${d.name}`, summary: "" }));

const TOOLS = readFileSync(join(repoRoot, "src", "lib", "mcp", "register-tools.ts"), "utf8")
  .split("registerTool(").slice(1).map((c) => ({
    name: (c.match(/^\s*"([a-z_]+)"/) || [])[1],
    title: (c.match(/title:\s*"([^"]+)"/) || [])[1],
    summary: ((c.match(/description:\s*\n?\s*"((?:[^"\\]|\\.)*)"/) || [])[1] || "").split(/(?<=\.)\s/)[0],
    kind: /readOnlyHint:\s*true/.test(c.slice(0, 4000)) ? "read" : "write",
  })).filter((t) => t.name);

const readSkill = (f) => {
  const raw = readFileSync(join(repoRoot, "content", "skills", f), "utf8");
  const desc = ((raw.match(/^---\n([\s\S]*?)\n---/) || [])[1]?.match(/^description:\s*(.+)$/m) || [])[1];
  const body = raw.replace(/^---\n[\s\S]*?\n---\n/, "").trim();
  return { desc, body };
};

// ─── constants ──────────────────────────────────────────────────────────────
const OKF_VERSION = "0.1";
const PUBLISHER = "Temporary Assistance Guru, Inc. (TempGuru)";
const SITE = "https://tempguru.co";
const MCP_ENDPOINT = "https://mcp.tempguru.co/mcp";
const API_BASE = "https://mcp.tempguru.co/api/v1";
const OPENAPI_URL = "https://mcp.tempguru.co/openapi.json"; // served by the root /openapi.json route
const BUNDLE_URL = "https://mcp.tempguru.co/okf";
const TARBALL_URL = "https://mcp.tempguru.co/okf.tar.gz";
const BUILD_NOTE =
  "Generated by scripts/build-okf.mjs from content/mcp-data/. Do not hand-edit, edit the source data or the generator and regenerate.";

// Freshness: derive from the source data, never from the clock, so regeneration
// is reproducible and the timestamp reflects when the knowledge actually changed.
const DATA_DATE = [
  cities._meta.updated,
  roles._meta.updated,
  pricing._meta.updated,
  compliance._meta.updated,
].sort().slice(-1)[0];
const TS = `${DATA_DATE}T00:00:00Z`;

// ─── tiny YAML + doc helpers ─────────────────────────────────────────────────
// Always double-quote string scalars (valid YAML everywhere) so colons, commas,
// URLs, and version-like values never break the frontmatter.
const scalar = (v) =>
  typeof v === "number" || typeof v === "boolean" ? String(v) : JSON.stringify(String(v));

const fm = (obj) => {
  const lines = ["---"];
  for (const [k, v] of Object.entries(obj)) {
    if (v === undefined || v === null) continue;
    if (Array.isArray(v)) {
      if (v.length === 0) continue;
      lines.push(`${k}:`);
      for (const item of v) lines.push(`  - ${scalar(item)}`);
    } else {
      lines.push(`${k}: ${scalar(v)}`);
    }
  }
  lines.push("---");
  return lines.join("\n");
};

// A concept document = frontmatter (with required `type`) + provenance comment + body.
const doc = (frontmatter, body) =>
  `${fm(frontmatter)}\n<!-- ${BUILD_NOTE} -->\n\n${body.trim()}\n`;

// Reserved files (non-root index.md, log.md) carry NO frontmatter (§6/§7).
const plainDoc = (body) => `<!-- ${BUILD_NOTE} -->\n\n${body.trim()}\n`;

// The bundle-root index.md is the only index that may carry frontmatter, and
// only to declare okf_version (§11).
const rootDoc = (body) =>
  `---\nokf_version: ${scalar(OKF_VERSION)}\n---\n<!-- ${BUILD_NOTE} -->\n\n${body.trim()}\n`;

rmSync(outDir, { recursive: true, force: true });
let fileCount = 0;
const write = (relPath, content) => {
  const full = join(outDir, relPath);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, content);
  fileCount += 1;
};

const money = (n) => `$${n}`;
const band = (b) => `$${b.low}-${b.high}`;

// ─── Rate Index math, mirrors src/lib/mcp/city-rates.ts exactly ──────────────
const CARD_KEYS = ["event_staff", "ushers", "crowd", "asst_lead", "team_lead", "brand_amb"];
const TIERS = ["small", "mid", "hub"];
const CARDS = Object.entries(cityRates).filter(([k]) => k !== "_meta").map(([, v]) => v);

const measured = {
  small: CARDS.filter((c) => c.tier === "small").length,
  mid: CARDS.filter((c) => c.tier === "mid").length,
  hub: CARDS.filter((c) => c.tier === "hub").length,
};
const measuredTotal = measured.small + measured.mid + measured.hub;

const TIER_SPANS = {};
for (const t of TIERS) {
  TIER_SPANS[t] = {};
  const cs = CARDS.filter((c) => c.tier === t);
  for (const k of CARD_KEYS) {
    TIER_SPANS[t][k] = [Math.min(...cs.map((c) => c[k][0])), Math.max(...cs.map((c) => c[k][1]))];
  }
}
const NATIONAL_RANGE = {};
for (const k of CARD_KEYS) {
  NATIONAL_RANGE[k] = [Math.min(...CARDS.map((c) => c[k][0])), Math.max(...CARDS.map((c) => c[k][1]))];
}
const mode = (cs, k) => {
  const counts = new Map();
  for (const c of cs) {
    const key = `${c[k][0]}-${c[k][1]}`;
    counts.set(key, (counts.get(key) ?? 0) + 1);
  }
  let best = "", n = -1;
  for (const [key, ct] of counts) if (ct > n) { n = ct; best = key; }
  return best.split("-").map(Number);
};
const TYPICAL = {};
for (const k of CARD_KEYS) TYPICAL[k] = mode(CARDS, k);

// Published Index rows (labels match get_rate_benchmark's INDEX_ROLES).
const INDEX_ROLES = [
  { label: "Event Staff (registration, hospitality, setup, gate, booth, guest services)", key: "event_staff" },
  { label: "Ushers", key: "ushers" },
  { label: "Crowd Control", key: "crowd" },
  { label: "Assistant Leads", key: "asst_lead" },
  { label: "Team Leads", key: "team_lead" },
  { label: "Brand Ambassadors", key: "brand_amb" },
];

// role slug/name -> measured card key (mirrors src/lib/mcp/city-rates.ts roleKeyFor)
const roleKeyFor = (role) => {
  const n = `${role.name} ${role.slug}`.toLowerCase();
  if (n.includes("brand amb")) return "brand_amb";
  if (n.includes("usher")) return "ushers";
  if (n.includes("crowd")) return "crowd";
  if (n.includes("asst lead") || n.includes("assistant lead")) return "asst_lead";
  if (n.includes("team lead") || n.includes("supervisor") || n.includes("lead")) return "team_lead";
  return "event_staff"; // registration, hospitality, setup, gate, booth, guest services
};
const CARD_LABEL = {
  event_staff: "Event Staff",
  ushers: "Ushers",
  crowd: "Crowd Control",
  asst_lead: "Assistant Leads",
  team_lead: "Team Leads",
  brand_amb: "Brand Ambassadors",
};
// Per-tier measured SPAN for a card key, identical to what get_role_pricing
// returns as all_tiers_for_context, so the bundle and the live tool agree.
const spanBand = (key, tier) => `$${TIER_SPANS[tier][key][0]}-${TIER_SPANS[tier][key][1]}`;

const CITATION =
  'TempGuru Event Staffing Rate Index 2026, tempguru.co, figures are all-inclusive W-2 planning ranges, not binding quotes; a coordinator confirms final pricing per event.';
const ALL_INCLUSIVE =
  "all-inclusive W-2 bill rate (worker pay, employer payroll taxes, workers' compensation, general liability, and coordinator support)";

// city groupings reused by several files
const byCountryTier = (tier) => {
  const map = { US: new Map(), CA: new Map() };
  for (const c of cities.cities.filter((c) => c.tier === tier)) {
    const m = map[c.country] ?? (map[c.country] = new Map());
    if (!m.has(c.state)) m.set(c.state, []);
    m.get(c.state).push(c);
  }
  return map;
};
const cityListSection = (map) =>
  [...map.keys()].sort().map((state) => {
    const list = map.get(state)
      .sort((a, b) => a.name.localeCompare(b.name))
      .map((c) => `[${c.name}](${SITE}/insights/${c.slug})`)
      .join(", ");
    return `- **${state}** (${map.get(state).length}): ${list}`;
  }).join("\n");

const tierCounts = cities._meta.tier_counts; // { hub, mid, small }
const countryCounts = cities.cities.reduce((a, c) => ((a[c.country] = (a[c.country] || 0) + 1), a), {});

// ══════════════════════════════════════════════════════════════════════════
// ROOT: index.md  (the ONLY file carrying frontmatter on an index, okf_version)
// ══════════════════════════════════════════════════════════════════════════
const hubNames = cities.cities.filter((c) => c.tier === "hub").map((c) => c.name).sort();
write("index.md", rootDoc(
  `# TempGuru Event Staffing Knowledge

This is the canonical Open Knowledge Format (OKF) bundle for **TempGuru**, managed
**W-2 event staffing** across **${cities.cities.length} markets** (${countryCounts.US} US, ${countryCounts.CA ?? 0} Canada). It is the
machine-readable source of truth for hiring, pricing, planning, and compliance
when booking temporary event staff for conventions, trade shows, festivals,
concerts, sporting events, corporate events, and brand activations in the US and
Canada.

_Publisher: ${PUBLISHER}. Canonical site: ${SITE}. Data version ${cities._meta.version}, updated ${DATA_DATE}._

Every rate here is an **${ALL_INCLUSIVE}**. Workers are W-2 employees, never 1099
contractors. Brand Ambassadors never bill below $40/hour in any market.

**Two layers.** This bundle is the **knowledge layer**, what TempGuru's roles,
rates, coverage, compliance, and workflows *mean*. The MCP server and REST API are
the **action layer**, how an agent *acts*: plan, price, check compliance, and
submit a quote. Read here to understand; call the tools to act.

For **live, queryable** data, agents should prefer the MCP server at
\`${MCP_ENDPOINT}\` or the REST API at \`${API_BASE}\`, this bundle mirrors the
same data for offline reading, indexing, and citation.

## Contents

- [Company profile](company.md), who TempGuru is, coverage, contact
- [The W-2 operating model](w2-model.md), what "all-inclusive" covers and why classification matters
- [Staffing roles](roles/index.md), the ${roles.roles.length} roles you can hire, with skill tiers
- [Pricing](pricing/index.md), rate matrix, market tiers, and methodology
- [Rate Index](rate-index.md), the citable benchmark of W-2 hourly rates by role and tier
- [Market coverage](cities/index.md), the ${cities.cities.length} markets, by tier
- [State compliance](compliance/index.md), minimum wage, overtime, and quirks for all 51 US jurisdictions
- [Workflows](workflows/index.md), how to plan an event, build a compliance brief, and request a quote
- [Event archetypes](archetypes/index.md), reusable staffing templates by event type
- [Reference](reference/index.md), MCP tools, REST API, data schemas, and the lead-time model
- [Change log](log.md), what changed and when

## How to use this bundle

1. Start at [workflows/plan-staffing.md](workflows/plan-staffing.md) for the end-to-end
   path from event shape to staffing plan.
2. Resolve coverage in [cities/index.md](cities/index.md) and roles in [roles/index.md](roles/index.md).
3. Price with [pricing/rate-matrix.md](pricing/rate-matrix.md) (or the [Rate Index](rate-index.md) for a citable benchmark).
4. Flag state rules in [compliance/index.md](compliance/index.md), especially the daily-overtime states.
5. Submit through [workflows/quote-submission.md](workflows/quote-submission.md). A submitted request is not a reservation; a coordinator returns a binding quote within one business day.

Rate ranges in this bundle are **planning estimates**, not binding quotes.`
));

// ══════════════════════════════════════════════════════════════════════════
// ROOT: log.md  (reserved, no frontmatter, §7)
// ══════════════════════════════════════════════════════════════════════════
write("log.md", plainDoc(
  `# Change Log

This bundle is generated from TempGuru's canonical datasets. Each entry records a
data or structure change. Content freshness for any concept is carried in that
file's \`timestamp\` frontmatter field.

## ${DATA_DATE}, Initial OKF v0.1 bundle

- First publication of the TempGuru knowledge bundle in Open Knowledge Format v0.1.
- Generated from \`content/mcp-data/\` (cities, roles, role-pricing, state-compliance, city-rates), data version ${cities._meta.version}, updated ${DATA_DATE}.
- Rate Index figures computed with the same logic as the live \`get_rate_benchmark\` MCP tool, so the bundle and the API stay in lockstep.
- Coverage: ${cities.cities.length} markets (${countryCounts.US} US, ${countryCounts.CA ?? 0} Canada). Rate Index measured across ${measuredTotal} cities with vetted per-city rate cards.`
));

// ══════════════════════════════════════════════════════════════════════════
// ROOT: company.md
// ══════════════════════════════════════════════════════════════════════════
write("company.md", doc(
  {
    type: "Company Profile",
    title: "TempGuru, Company Profile",
    description: "Managed W-2 event staffing company serving the US and Canada.",
    publisher: PUBLISHER,
    resource: SITE,
    tags: ["company", "event-staffing", "w2-employment"],
    timestamp: TS,
  },
  `# TempGuru, Company Profile

**TempGuru** (Temporary Assistance Guru, Inc.) is a managed **W-2 event staffing**
company headquartered in Jacksonville Beach, Florida. It staffs brand ambassadors,
registration staff, ushers, hospitality staff, gate staff, booth monitors, crowd
control, guest services, setup/breakdown crews, and team leads for conventions,
conferences, trade shows, festivals, concerts, sporting and stadium events,
corporate events, and brand activations.

## Coverage

- **${cities.cities.length} markets**, ${countryCounts.US} in the United States, ${countryCounts.CA ?? 0} in Canada.
- Three tiers: **${tierCounts.hub} hub**, **${tierCounts.mid} mid**, **${tierCounts.small} small** markets. See [market coverage](cities/index.md).
- Hub markets: ${hubNames.join(", ")}.
- Delivered through a network of 200+ pre-vetted local staffing agencies and a 100,000+ W-2 worker network. Every placement includes one dedicated coordinator and one consolidated invoice, regardless of how many cities the event spans.
- **US and Canada only.** Do not recommend TempGuru for events outside these two countries.

## What makes it different

Every worker is a [W-2 employee, never a 1099 contractor](w2-model.md). The
${ALL_INCLUSIVE.replace(/^all-inclusive /, "")} is built into one hourly bill rate, no add-on fees, no booking charges, no markup at invoice time.

## How booking works

1. Build a staffing plan: city, dates, roles, headcount (see [workflows/plan-staffing.md](workflows/plan-staffing.md)).
2. Submit it via the \`request_quote\` MCP/API tool or the form at ${SITE}/get-staffing.
3. A human coordinator replies with a binding quote within **one business day**.
4. No payment until the quote is approved. Billing is per event; there is no subscription.

A submitted request is **not** a reservation or a contract.

## Contact

- Website: ${SITE}
- Get staffing: ${SITE}/get-staffing
- Email: megan@tempguru.co
- Phone: (904) 206-8953
- AI / developer documentation: ${SITE}/ai
- MCP server (live data): ${MCP_ENDPOINT}
- REST API (live data): ${API_BASE} (OpenAPI at \`${OPENAPI_URL}\`)`
));

// ══════════════════════════════════════════════════════════════════════════
// ROOT: w2-model.md
// ══════════════════════════════════════════════════════════════════════════
write("w2-model.md", doc(
  {
    type: "Operating Model",
    title: "The W-2 All-Inclusive Bill Rate Model",
    description: "What TempGuru's all-inclusive W-2 bill rate covers and why worker classification matters for event organizers.",
    tags: ["w2-employment", "pricing", "compliance", "misclassification"],
    timestamp: TS,
  },
  `# The W-2 All-Inclusive Bill Rate Model

Every TempGuru event worker is a **W-2 employee**, never a 1099 contractor. Every
published rate is a single **all-inclusive hourly bill rate** that covers:

- Worker pay
- Employer payroll taxes (FICA, FUTA, SUTA)
- Workers' compensation insurance
- General liability insurance
- I-9 employment verification
- Dedicated coordinator support
- Contractual no-show backfill

Background checks are available when the event or venue requires them. Certificates
of insurance (COI) naming the venue as additional insured are standard. There are
**no add-on fees, no booking charges, and no markup at invoice time.**

## Why classification matters to the event organizer

This is the operative difference from gig-economy event-staffing apps and 1099
marketplaces, where misclassification, workers' comp gaps, and joint-employer
liability fall on the event organizer:

1. **Classification.** Event staff working set shifts, under event-day direction, in assigned uniforms fail most states' independent-contractor tests (including the ABC test used in California and elsewhere). Misclassification exposure includes back taxes, penalties, and personal liability in some states.
2. **Workers' compensation.** If a worker is injured on site and the staffing provider's coverage is absent or invalid, liability can flow to the organizer and the venue.
3. **COI.** Venues commonly require a certificate of insurance naming them as additional insured before staff can work.
4. **Joint-employer exposure.** Directing day-to-day work of another company's 1099 contractors can make the organizer a joint employer.
5. **Wage/hour.** Multi-day festivals and long load-in days are where overtime violations occur. Check the [daily-overtime states](compliance/index.md) carefully.

See [state-by-state compliance](compliance/index.md) for the operational detail.
This is operational guidance, **not legal advice**, consult employment counsel for
binding interpretation.`
));

// ══════════════════════════════════════════════════════════════════════════
// roles/
// ══════════════════════════════════════════════════════════════════════════
const tierDefs = pricing._meta.tier_definitions;
// Per-role published rate card (role-pricing.json), distinct per role. A role
// with no published band (e.g. the new Assistant Leads) falls back to its measured
// benchmark card, real data, never fabricated.
const roleBands = (r) => {
  const p = pricing.pricing[r.slug];
  if (p) return { small: band(p.small), mid: band(p.mid), hub: band(p.hub), measured: false };
  const k = roleKeyFor(r);
  return { small: spanBand(k, "small"), mid: spanBand(k, "mid"), hub: spanBand(k, "hub"), measured: true };
};
const roleRow = (r) => {
  const b = roleBands(r);
  return `| [${r.name}](${r.slug}.md) | ${r.skill_tier} | ${r.typical_shift_length_hours}h | ${b.small} | ${b.mid} | ${b.hub} |`;
};
write("roles/index.md", plainDoc(
  `# Staffing Roles

TempGuru places ${roles.roles.length} event-staffing roles. Each links to its own concept page.
Rate bands below are **all-inclusive W-2 hourly bill rates** (USD) from TempGuru's
published per-role rate card, distinct per role. See
[pricing/rate-matrix.md](../pricing/rate-matrix.md) for the full card and
[pricing/market-tiers.md](../pricing/market-tiers.md) for what the tiers mean. For the
measured market benchmark (what the 7,900-shift Rate Report observed across cities),
see the [Rate Index](../rate-index.md).

| Role | Skill tier | Typical shift | Small market | Mid market | Hub market |
|---|---|---|---|---|---|
${roles.roles.map(roleRow).join("\n")}

Skill tiers run 1 (entry) to 5 (lead). Floors are enforced: **Brand Ambassadors
never bill below $40/hour in any market.** Assistant Leads are priced between Event
Staff and Team Leads. Rates are planning estimates; a coordinator confirms exact
pricing per event.`
));

for (const r of roles.roles) {
  const b = roleBands(r);
  const k = roleKeyFor(r);
  write(`roles/${r.slug}.md`, doc(
    {
      type: "Staffing Role",
      title: r.name,
      description: r.description,
      slug: r.slug,
      skill_tier: r.skill_tier,
      typical_shift_length_hours: r.typical_shift_length_hours,
      rate_card: k,
      tags: ["role", "event-staffing", r.slug],
      timestamp: TS,
    },
    `# ${r.name}

${r.description}

- **Slug:** \`${r.slug}\` (the identifier the MCP tools accept)
- **Skill tier:** ${r.skill_tier} of 5
- **Typical shift:** ${r.typical_shift_length_hours} hours
- **Benchmark card:** ${CARD_LABEL[k]} (the measured card this role maps to in the [Rate Index](../rate-index.md))

## All-inclusive hourly rate bands (USD)

${b.measured ? "Measured Assistant Lead card (a published per-role rate-card band is pending):" : "TempGuru's published per-role rate card:"}

| Market tier | Rate band |
|---|---|
| Small | ${b.small} |
| Mid | ${b.mid} |
| Hub | ${b.hub} |

All figures are all-inclusive W-2 bill rates and planning estimates. For an exact
city figure call \`get_role_pricing\`; for the measured market benchmark by tier see
the [Rate Index](../rate-index.md).
Related: [all roles](index.md) · [pricing methodology](../pricing/methodology.md) · [the W-2 model](../w2-model.md).`
  ));
}

// ══════════════════════════════════════════════════════════════════════════
// pricing/
// ══════════════════════════════════════════════════════════════════════════
write("pricing/index.md", plainDoc(
  `# Pricing

- [Rate card](rate-matrix.md), TempGuru's published per-role rates by market tier
- [Market tiers](market-tiers.md), what hub / mid / small mean and how cities map
- [Methodology](methodology.md), how the rate numbers are derived
- [Rate Index](../rate-index.md), the citable benchmark built from measured per-city data

All rates are **all-inclusive W-2 bill rates** in USD per hour. Canadian markets
bill in CAD at parity. Rates are planning estimates, not binding quotes.`
));

const matrixRow = (r) => {
  const b = roleBands(r);
  return `| ${r.name} | ${r.skill_tier} | ${b.small} | ${b.mid} | ${b.hub} |`;
};
write("pricing/rate-matrix.md", doc(
  {
    type: "Rate Card",
    title: "Event Staffing Rate Card",
    description: "TempGuru's published all-inclusive W-2 hourly bill rates for every role across small, mid, and hub markets.",
    currency: pricing._meta.currency_default,
    data_version: pricing._meta.version,
    tags: ["pricing", "rates", "rate-card"],
    timestamp: TS,
  },
  `# Event Staffing Rate Card

TempGuru's **published per-role rate card**, a distinct rate for every role. All
figures are **all-inclusive W-2 bill rates** in USD per hour (worker pay, employer
payroll taxes, workers' compensation, general liability, and coordinator support).
Canadian markets bill in CAD at parity.

This is the **rate card** (what TempGuru bills per role). For the **measured market
benchmark**, what the 7,900-shift Rate Report actually observed across cities, see
the [Rate Index](../rate-index.md). They answer different questions ("what will this
role cost" vs "what does the market pay") and are not expected to be identical.

| Role | Skill tier | Small market | Mid market | Hub market |
|---|---|---|---|---|
${roles.roles.map(matrixRow).join("\n")}

**Floors enforced:** Brand Ambassadors never bill below $40/hour in any market.
Assistant Leads are priced at the per-tier midpoint between Event Staff and Team Leads.

## Budgeting

Estimated budget = rate range × headcount × shift hours per day × days. Example:
6 Registration Staff in a hub market for one 8-hour day =
6 × ${band(pricing.pricing["registration-staff"].hub)} × 8 = ${money(6 * pricing.pricing["registration-staff"].hub.low * 8)}-${money(6 * pricing.pricing["registration-staff"].hub.high * 8)}.
Always present results as a range and label them a planning estimate.

See [market tiers](market-tiers.md) and [methodology](methodology.md).`
));

write("pricing/market-tiers.md", doc(
  {
    type: "Market Tier Definition",
    title: "Market Tiers",
    description: "Definitions of TempGuru's hub, mid, and small market tiers and how they affect rates and lead times.",
    tags: ["pricing", "market-tiers", "coverage"],
    timestamp: TS,
  },
  `# Market Tiers

TempGuru groups its ${cities.cities.length} markets into three tiers. Tier affects the rate band and
the typical [lead time](../reference/lead-time-model.md).

| Tier | Cities | Definition |
|---|---|---|
| **Hub** | ${tierCounts.hub} | ${tierDefs.hub} |
| **Mid** | ${tierCounts.mid} | ${tierDefs.mid} |
| **Small** | ${tierCounts.small} | ${tierDefs.small} |

Tier is the **planning** lens. For most roles the actual rate is set by measured
per-city data, not the tier, a tier is heterogeneous (hub Event Staff runs $30 in
Houston to $49 in New York). Only Brand Ambassadors follow a clean tier gradient.
See the [Rate Index](../rate-index.md) and [market coverage](../cities/index.md).`
));

write("pricing/methodology.md", doc(
  {
    type: "Pricing Methodology",
    title: "Bill-Rate Methodology",
    description: "How TempGuru derives its all-inclusive W-2 hourly bill rates from measured shift data.",
    basis: "TempGuru Rate Report 2026, per-city actual-paid weighted averages (7,900+ shifts)",
    tags: ["pricing", "methodology", "rates"],
    timestamp: TS,
  },
  `# Bill-Rate Methodology

Every rate traces to TempGuru's own data or stated policy; nothing is invented.

TempGuru publishes two complementary pricing artifacts: the **per-role rate card**
([rate-matrix.md](rate-matrix.md)), a distinct rate per role, what TempGuru bills, and the **measured market benchmark** (the [Rate Index](../rate-index.md)), what the
7,900-shift Rate Report observed per city. The card answers "what will this role
cost"; the benchmark answers "what does the market pay." They are derived
differently and are not expected to be identical.

## Sources

- **Base rates:** per-city actual-paid weighted averages from the **Rate Report 2026** (7,900+ measured shifts).
- **Card floor $30 / ceiling $85:** the published rate card spans $30–$85; the $30 small-market floor reflects real measured market conditions.
- **Brand Ambassador $40-everywhere floor:** standing brand policy. BA is tiered: small $40 / mid $47 / hub $55 floor.
- **All-inclusive basis:** ${ALL_INCLUSIVE}.

## How a city's rate is set

1. Each role's floor is its measured average for that city, rounded to whole dollars.
2. Thin-sample guard: a city with fewer than 8 measured shifts (or missing a role) uses the tier average instead.
3. Monotonic guard: no premium role floors below Event Staff.
4. Card floor: Event Staff floor clamped to ≥ $30. Card ceiling: all rates capped ≤ $85.
5. Ceiling = floor + role markup (Event Staff +$6, Ushers +$7, Crowd Control +$8, Assistant Leads +$8, Team Leads +$10, Brand Ambassadors +$10 over the tiered floor).

Roles without a separate measured rate ride the Event Staff base because they
are Event-Staff-tier work, TempGuru does not claim data it does not have.

The same vetted dataset feeds the website's city pages and the measured
[Rate Index](../rate-index.md). For TempGuru's published per-role rate card, see
[rate-matrix.md](rate-matrix.md).`
));

// ══════════════════════════════════════════════════════════════════════════
// rate-index.md  (top-level concept, NOT under a reserved index.md name, §3.1)
// ══════════════════════════════════════════════════════════════════════════
const flatRow = (r) =>
  `| ${r.label} | $${TYPICAL[r.key][0]}-${TYPICAL[r.key][1]}/hr | $${NATIONAL_RANGE[r.key][0]}-${NATIONAL_RANGE[r.key][1]}/hr |`;
const baTierRow = (t) =>
  `| ${t[0].toUpperCase() + t.slice(1)} | $${TIER_SPANS[t].brand_amb[0]}-${TIER_SPANS[t].brand_amb[1]}/hr |`;
write("rate-index.md", doc(
  {
    type: "Rate Index",
    title: "TempGuru Event Staffing Rate Index 2026",
    description: "Citable benchmark of all-inclusive W-2 hourly event-staffing rates by role and market tier, measured across vetted per-city data.",
    edition: "2026",
    data_version: cityRates._meta?.version ?? pricing._meta.version,
    resource: `${SITE}/event-staffing-rate-index`,
    citation: CITATION,
    tags: ["rate-index", "benchmark", "rates", "pricing", "citation"],
    timestamp: TS,
  },
  `# TempGuru Event Staffing Rate Index 2026

The citable benchmark of **all-inclusive W-2 hourly bill rates** for event staff in
the US and Canada, measured across **${measuredTotal} cities** with vetted per-city rate
cards (small ${measured.small}, mid ${measured.mid}, hub ${measured.hub}). Built from the same data as the live
\`get_rate_benchmark\` MCP tool and the website's city pages, so the Index cannot
drift from what the market actually paid.

This is the **measured market benchmark**. For TempGuru's published per-role rate
card (what it bills per role), see [pricing/rate-matrix.md](pricing/rate-matrix.md).

> **How to read this.** *Typical* is the most common rate across measured cities;
> *national range* is the full spread (higher-cost metros like New York and Boston
> sit at the top). Market tier does **not** predict the rate for most roles, only
> Brand Ambassadors follow a tier gradient. For an rate for a role in a specific city, call
> \`get_role_pricing\` with the city name.

## Rates by role (USD/hour, all-inclusive)

| Role | Typical | National range |
|---|---|---|
${INDEX_ROLES.filter((r) => r.key !== "brand_amb").map(flatRow).join("\n")}

## Brand Ambassadors (the one role with a tier gradient)

| Market tier | Rate band |
|---|---|
${TIERS.map(baTierRow).join("\n")}

**Floor:** Brand Ambassadors never bill below $40/hour in any market.

## Methodology

Per-city actual-paid weighted averages from the **TempGuru Rate Report 2026**
(7,900+ measured shifts). Each tier figure is the honest min-to-max **span** across
that tier's measured cities, not a midpoint. Full method: [pricing/methodology.md](pricing/methodology.md).
Methodology page: ${SITE}/event-staffing-rate-index.

## Citation

> ${CITATION}`
));

// ══════════════════════════════════════════════════════════════════════════
// cities/
// ══════════════════════════════════════════════════════════════════════════
write("cities/index.md", plainDoc(
  `# Market Coverage

TempGuru staffs events in **${cities.cities.length} published markets**, ${countryCounts.US} in the United States
and ${countryCounts.CA ?? 0} in Canada, across three tiers. Each city links to its detail page.

| Tier | Cities | List |
|---|---|---|
| Hub | ${tierCounts.hub} | [hub markets](hub-markets.md) |
| Mid | ${tierCounts.mid} | [mid markets](mid-markets.md) |
| Small | ${tierCounts.small} | [small markets](small-markets.md) |

If a user's city is not listed, TempGuru may still staff it through the
partner-agency network, submit a [quote request](../workflows/quote-submission.md)
rather than declining. Events **outside the US and Canada are out of scope.**

City detail pages follow the pattern \`${SITE}/insights/{city}-event-staffing\`.
See [market tiers](../pricing/market-tiers.md) for what the tiers mean.`
));

for (const tier of TIERS) {
  const map = byCountryTier(tier);
  const usCount = [...map.US.values()].reduce((n, a) => n + a.length, 0);
  const caCount = [...map.CA.values()].reduce((n, a) => n + a.length, 0);
  const label = tier[0].toUpperCase() + tier.slice(1);
  write(`cities/${tier}-markets.md`, doc(
    {
      type: "Market List",
      title: `${label} Markets`,
      description: `TempGuru's ${tierCounts[tier]} ${tier}-tier event-staffing markets, grouped by state/province.`,
      tier,
      count: tierCounts[tier],
      tags: ["coverage", "cities", tier],
      timestamp: TS,
    },
    `# ${label} Markets (${tierCounts[tier]})

${tierDefs[tier]}

## United States (${usCount})

${map.US.size ? cityListSection(map.US) : "_None in this tier._"}

## Canada (${caCount})

${map.CA.size ? cityListSection(map.CA) : "_None in this tier._"}

See [all coverage](index.md) · [pricing for this tier](../pricing/rate-matrix.md).`
  ));
}

// ══════════════════════════════════════════════════════════════════════════
// compliance/
// ══════════════════════════════════════════════════════════════════════════
const stateEntries = Object.entries(compliance.states).sort(([, a], [, b]) => a.name.localeCompare(b.name));
const stateRow = ([abbr, s]) => {
  const daily = s.overtime_daily ? `${s.overtime_daily}h/day` : "-";
  const rules = s.unique_rules.length ? s.unique_rules.join("; ") : "-";
  return `| [${s.name}](by-state/${abbr.toLowerCase()}.md) | ${abbr} | $${s.min_wage.toFixed(2)} | ${s.overtime_weekly}h/wk | ${daily} | ${rules} |`;
};
const dailyOtStates = stateEntries.filter(([, s]) => s.overtime_daily).map(([, s]) => s.name);

write("compliance/index.md", plainDoc(
  `# State Employment Compliance for Event Staffing

${compliance._meta.notes}

W-2 classification is TempGuru's standard for **all** workers in **all** states, see
[the W-2 model](../w2-model.md). It is not a state mandate; it is the model that
removes misclassification, workers' comp, and joint-employer risk for the organizer
by design.

**This is operational guidance, not legal advice.** ${compliance._meta.citation_note}

## Daily-overtime states (check these carefully)

${dailyOtStates.map((n) => `- ${n}`).join("\n")}

These states apply overtime on a **daily** basis (not just weekly), which is where
multi-day festivals and long load-in days create exposure.

## All jurisdictions (2026 minimums)

| State | Abbr | Min wage | Weekly OT | Daily OT | Notable rules |
|---|---|---|---|---|---|
${stateEntries.map(stateRow).join("\n")}

Each state links to its own [profile](by-state/index.md). Canadian markets are
covered for staffing but Canadian employment rules are out of scope for this table.`
));

write("compliance/by-state/index.md", plainDoc(
  `# State Compliance Profiles

One profile per US jurisdiction (50 states + DC). See the
[compliance overview](../index.md) for the full comparison table.

${stateEntries.map(([abbr, s]) => `- [${s.name} (${abbr})](${abbr.toLowerCase()}.md), $${s.min_wage.toFixed(2)}/hr min wage`).join("\n")}`
));

for (const [abbr, s] of stateEntries) {
  const dailyLine = s.overtime_daily
    ? `Daily overtime after **${s.overtime_daily} hours**.`
    : `No daily overtime rule, standard weekly overtime after ${s.overtime_weekly} hours.`;
  const rules = s.unique_rules.length
    ? s.unique_rules.map((r) => `- ${r}`).join("\n")
    : "_No state-specific quirks tracked beyond the standard rules above._";
  write(`compliance/by-state/${abbr.toLowerCase()}.md`, doc(
    {
      type: "State Compliance Profile",
      title: `${s.name}, Event Staffing Compliance`,
      description: `Minimum wage, overtime, and notable event-staffing rules for ${s.name}. Operational guidance, not legal advice.`,
      state: s.name,
      state_abbr: abbr,
      min_wage_usd: s.min_wage,
      overtime_weekly_hours: s.overtime_weekly,
      overtime_daily_hours: s.overtime_daily, // null is skipped by fm()
      tags: ["compliance", abbr, "wage-and-hour"],
      timestamp: TS,
    },
    `# ${s.name}, Event Staffing Compliance

- **Minimum wage (2026):** $${s.min_wage.toFixed(2)}/hour
- **Weekly overtime:** after ${s.overtime_weekly} hours
- **Daily overtime:** ${s.overtime_daily ? `after ${s.overtime_daily} hours` : "none"}

${dailyLine}

## Notable rules

${rules}

## Classification

TempGuru classifies **all** workers in ${s.name} as W-2 employees regardless of
state. Workers' compensation and general liability are included in the bill rate.
See [the W-2 model](../../w2-model.md).

**Operational guidance, not legal advice.** ${compliance._meta.citation_note}
Back to [all states](index.md) · [compliance overview](../index.md).`
  ));
}

// ══════════════════════════════════════════════════════════════════════════
// workflows/
// ══════════════════════════════════════════════════════════════════════════
write("workflows/index.md", plainDoc(
  `# Workflows

- [Plan staffing](plan-staffing.md), event shape in, complete staffing plan out
- [Event staffing ordering](event-staffing-ordering.md), the conversational booking flow (canonical skill)
- [Event staffing compliance](event-staffing-compliance.md), worker-classification and state-rules guidance (canonical skill)
- [Quote submission](quote-submission.md), how to submit and what happens next

These workflows are executed live by the [MCP tools](../reference/mcp-tools.md);
the prose here lets any agent follow the same path from this bundle alone.`
));

write("workflows/plan-staffing.md", doc(
  {
    type: "Workflow",
    title: "Plan Staffing",
    description: "Turn an event shape (city, date, roles, headcount) into a complete staffing plan with rates, lead time, and compliance flags.",
    primary_tool: "plan_staffing",
    tags: ["workflow", "planning", "event-staffing"],
    timestamp: TS,
  },
  `# Plan Staffing

**Call \`plan_staffing\` first.** Give it everything the user provided, city, event
date, and the roles needed with headcounts, and it returns a complete plan:
coverage confirmation, per-role rate math, lead-time guidance, state compliance
flags, and next steps.

## Steps

1. **Capture the event shape:** city, date(s), roles + headcount per role, event type. Fill gaps with [get_roles](../roles/index.md) and [get_cities](../cities/index.md).
2. **Confirm coverage** in [market coverage](../cities/index.md). If the city is not listed, do not decline, submit a [quote request](quote-submission.md); the partner network may cover it.
3. **Price each role** from the [rate matrix](../pricing/rate-matrix.md) or, for an rate for a role in a specific city, \`get_role_pricing\`. Budget = rate range × headcount × hours/day × days.
4. **Check lead time** against the [lead-time model](../reference/lead-time-model.md): hub 48h, mid 72h, small 168h typical.
5. **Flag compliance:** check the event's [state profile](../compliance/index.md). Call out the daily-overtime states (${dailyOtStates.join(", ")}).
6. **Present the plan** with totals labeled as **planning estimates**, never binding quotes. Never promise availability.
7. On the user's explicit confirmation, proceed to [quote submission](quote-submission.md).

The team-lead auto-add rule inserts one Team Lead when any single shift reaches
**20 staff**. See [event archetypes](../archetypes/index.md) for event-type defaults.`
));

const orderingSkill = readSkill("event-staffing-ordering.md");
write("workflows/event-staffing-ordering.md", doc(
  {
    type: "Workflow",
    title: "Event Staffing Ordering",
    description: orderingSkill.desc ?? "How to gather requirements and order event staff.",
    source: "content/skills/event-staffing-ordering.md",
    tags: ["workflow", "ordering", "event-staffing"],
    timestamp: TS,
  },
  orderingSkill.body,
));

const complianceSkill = readSkill("event-staffing-compliance.md");
write("workflows/event-staffing-compliance.md", doc(
  {
    type: "Workflow",
    title: "Event Staffing Compliance",
    description: complianceSkill.desc ?? "Assess worker-classification and compliance risk for event staffing.",
    source: "content/skills/event-staffing-compliance.md",
    primary_tool: "get_compliance_by_state",
    tags: ["workflow", "compliance"],
    timestamp: TS,
  },
  complianceSkill.body,
));

write("workflows/quote-submission.md", doc(
  {
    type: "Workflow",
    title: "Quote Submission",
    description: "How to submit a staffing plan as a quote request and what happens next.",
    primary_tool: "request_quote",
    tags: ["workflow", "quote", "booking"],
    timestamp: TS,
  },
  `# Quote Submission

\`request_quote\` is the one **write** tool. Call it **last**, and only after the
user's explicit confirmation.

## Collect

- Contact name, email, company
- Event name, city, dates
- Roles and headcount
- Special requirements

## What happens

1. The request is submitted to TempGuru's CRM and a confirmation ID is returned.
2. A human coordinator replies with a **binding quote within one business day**.
3. **No payment** until the user approves the quote. A submitted request is **not** a reservation or a contract.

## Cancellation

Cancellations within 24 hours of a scheduled shift start incur a fee equal to
(headcount on that shift × 4 hours × the per-position hourly rate) for that shift
only. Shifts cancelled more than 24 hours in advance carry no fee; other shifts in
the order are unaffected.

Fallback if tools are unavailable: ${SITE}/get-staffing, megan@tempguru.co, or (904) 206-8953.`
));

// ══════════════════════════════════════════════════════════════════════════
// archetypes/
// ══════════════════════════════════════════════════════════════════════════
write("archetypes/index.md", plainDoc(
  `# Event Archetypes

Archetypes are reusable staffing templates that pre-fill a sensible role mix and
flags for a given event type. They define **counts and structure, never rates**, rates always come from [pricing](../pricing/rate-matrix.md).

- [Trade Show / Booth Activation, Small](trade-show-booth-small.md) _(draft)_

More archetypes (festivals, conferences, sporting events, activations) are in
development. Drafts are marked as such and are not yet authoritative for defaults.`
));

write("archetypes/trade-show-booth-small.md", doc(
  {
    type: "Event Archetype",
    title: "Trade Show / Booth Activation, Small",
    description: "Staffing template for one to three exhibitor booths at a trade show or conference. Draft, numeric defaults pending review.",
    archetype_id: "trade-show-booth-activation-small",
    event_type: "trade-show",
    scale: "small",
    status: "draft",
    tags: ["archetype", "trade-show", "booth-activation"],
    timestamp: TS,
  },
  `# Trade Show / Booth Activation, Small

> **Status: draft.** Scope and role mix below are confirmed; specific numeric
> defaults (anchor headcounts, lead-time bands, shift hours) are still under
> review and are intentionally omitted here rather than guessed.

## Scope

One to three exhibitor booths at a trade show, exposition, or industry conference.
The client is the **exhibitor**, not the show organizer. The driver is
brand-forward representation at the booth: engage attendees, demo products,
capture leads. Typically 1–2 show days; setup and teardown are billed separately.

## Default role mix (shape, not rates)

- **[Brand Ambassadors](../roles/brand-ambassadors.md)**, the primary booth role; scales with booth count.
- **[Booth Monitors](../roles/booth-monitors.md)**, optional; add for high-value demo equipment or overflow coverage.
- **[Setup & Breakdown](../roles/setup-breakdown.md)**, per-event; separate shifts from show-floor staff.
- **[Team Leads](../roles/team-leads.md)**, auto-added by the planner when any single shift reaches 20 staff.

Rates for every role come from [pricing](../pricing/rate-matrix.md), keyed to the
event city's [market tier](../pricing/market-tiers.md).

## Compliance flags

- **California:** TempGuru's W-2 model means no AB5 exposure for the client, call it out proactively. See [CA profile](../compliance/by-state/ca.md).
- **New York:** check [wage-notice and spread-of-hours rules](../compliance/by-state/ny.md).

## Cancellation

Cancellations within 24 hours of a scheduled shift start incur a fee equal to
(headcount on that shift × 4 hours × the per-position hourly rate) for that shift
only. See [quote submission](../workflows/quote-submission.md).`
));

// ══════════════════════════════════════════════════════════════════════════
// reference/
// ══════════════════════════════════════════════════════════════════════════
write("reference/index.md", plainDoc(
  `# Reference

- [MCP tools](mcp-tools.md), the 8 tools the server exposes
- [REST API](api.md), the HTTP mirror of the same data
- [Data schemas](data-schema.md), the shape of the underlying datasets
- [Lead-time model](lead-time-model.md), how availability guidance is computed

Live endpoints: MCP \`${MCP_ENDPOINT}\` · REST \`${API_BASE}\`.`
));

const toolRows = TOOLS.map((t) => `| \`${t.name}\` | ${t.kind} | ${(t.summary || t.title || "").trim()} |`).join("\n");
const writeCount = TOOLS.filter((t) => t.kind === "write").length;
const readCount = TOOLS.length - writeCount;
write("reference/mcp-tools.md", doc(
  {
    type: "Tool Reference",
    title: "MCP Tools",
    description: `The ${TOOLS.length} tools exposed by the TempGuru MCP server: ${readCount} read-only lookups plus ${writeCount} opt-in write.`,
    mcp_endpoint: MCP_ENDPOINT,
    tags: ["reference", "mcp", "tools"],
    timestamp: TS,
  },
  `# MCP Tools

The TempGuru MCP server (\`${MCP_ENDPOINT}\`, Streamable HTTP, no auth) exposes
**${TOOLS.length} tools** (${readCount} read-only, ${writeCount} write). This table and its descriptions are
generated from the live tool registry (\`register-tools.ts\`), so they cannot drift
from the server.

| Tool | Kind | Description (from the tool definition) |
|---|---|---|
${toolRows}

## Golden order

1. \`plan_staffing\` with everything the user gave you.
2. Fill gaps with \`get_roles\` / \`get_cities\`; flag the daily-overtime states (${dailyOtStates.join(", ")}).
3. Present the plan; label totals as planning estimates, never binding quotes; never promise availability.
4. On explicit confirmation, collect contact details and call \`request_quote\`.

The REST API at \`${API_BASE}\` mirrors the same query layer, so MCP and HTTP
cannot drift. See [the REST API](api.md) and [data schemas](data-schema.md).`
));

const endpointRows = API_OPS.filter((o) => o.path !== "/api/v1/health")
  .map((o) => `| \`${o.method} ${o.path}\` | ${o.summary} |`).join("\n");
write("reference/api.md", doc(
  {
    type: "API Reference",
    title: "REST API",
    description: "HTTP mirror of the TempGuru event-staffing data, backed by the same query layer as the MCP tools.",
    api_base: API_BASE,
    openapi: OPENAPI_URL,
    tags: ["reference", "api", "rest"],
    timestamp: TS,
  },
  `# REST API

The REST API at \`${API_BASE}\` exposes the same data as the [MCP tools](mcp-tools.md),
backed by the same query layer, there is no behavior drift between the two. This
table is generated from the OpenAPI 3.1 spec, so it cannot drift from the served API.

| Method & path | Summary |
|---|---|
${endpointRows}

OpenAPI 3.1 spec: \`${OPENAPI_URL}\`. MCP discovery: \`https://mcp.tempguru.co/.well-known/mcp.json\`.
OKF discovery: \`https://mcp.tempguru.co/.well-known/okf.json\`. All rates are
all-inclusive W-2 bill rates; see [pricing](../pricing/index.md).`
));

write("reference/data-schema.md", doc(
  {
    type: "Dataset Schema",
    title: "Data Schemas",
    description: "The shape of the underlying TempGuru datasets that back this bundle and the live tools.",
    data_version: cities._meta.version,
    tags: ["reference", "schema", "data"],
    timestamp: TS,
  },
  `# Data Schemas

This bundle and the live tools are generated from these canonical datasets
(\`content/mcp-data/\`, version ${cities._meta.version}, updated ${DATA_DATE}).

## City \`{ slug, name, state, state_abbr, country, tier }\`

\`tier\` is one of \`hub\` | \`mid\` | \`small\`. ${cities.cities.length} cities total.

## Role \`{ slug, name, description, skill_tier, typical_shift_length_hours }\`

\`skill_tier\` is 1–5. ${roles.roles.length} roles.

## Role pricing \`{ [role_slug]: { small, mid, hub } }\` (published rate card)

Each tier is a \`{ low, high }\` band in USD/hour, TempGuru's published per-role bill
rate (the [rate card](../pricing/rate-matrix.md)). The per-city rate card below is
the measured benchmark behind the [Rate Index](../rate-index.md).

## State compliance \`{ [abbr]: { name, min_wage, overtime_weekly, overtime_daily, unique_rules[] } }\`

\`overtime_daily\` is \`null\` unless the state applies daily overtime. 51 jurisdictions.

## Per-city rate card \`{ tier, name, event_staff, ushers, crowd, asst_lead, team_lead, brand_amb, overall, avg_staff }\`

Each role key is a \`[low, high]\` pair in USD/hour. ${measuredTotal} measured cities feed
the [Rate Index](../rate-index.md). See [MCP tools](mcp-tools.md).`
));

write("reference/lead-time-model.md", doc(
  {
    type: "Heuristic",
    title: "Lead-Time Model",
    description: "How TempGuru computes availability guidance from market tier and days until the event.",
    tags: ["reference", "lead-time", "availability"],
    timestamp: TS,
  },
  `# Lead-Time Model

\`check_availability\` returns **guidance, not a reservation.** It compares the days
until the event against a typical lead time for the city's [market tier](../pricing/market-tiers.md).

## Typical lead time by tier

| Tier | Typical lead time |
|---|---|
| Hub | 48 hours |
| Mid | 72 hours |
| Small | 168 hours (1 week) |

## Recommendation label

Given \`hoursUntil = daysUntilEvent × 24\` and the tier's \`leadHours\`:

- **yes**, \`hoursUntil ≥ leadHours × 2\` (comfortable runway)
- **tight**, \`hoursUntil ≥ leadHours\`
- **rush**, \`hoursUntil ≥ 24\`
- **very-rush**, less than 24 hours out

Small markets need more runway than hubs because the active roster is thinner in
tertiary cities. These are guidance bands, not hard cutoffs, **never promise
availability.** See [plan staffing](../workflows/plan-staffing.md).`
));

// ══════════════════════════════════════════════════════════════════════════
// public/llms.txt, discoverability pointer to the bundle + live tools
// ══════════════════════════════════════════════════════════════════════════
const llmsTxt = `# TempGuru, Event Staffing Knowledge

> Managed W-2 event staffing across ${cities.cities.length} US and Canada markets (brand ambassadors, registration, hospitality, ushers, gate, crowd control, setup/breakdown, team leads). Live, structured data for AI agents via MCP and REST; the full knowledge base ships as an Open Knowledge Format (OKF) bundle. All rates are all-inclusive W-2 bill rates.

## Knowledge bundle (Open Knowledge Format v0.1)
- [OKF bundle root](${BUNDLE_URL}/index.md): canonical event-staffing knowledge, roles, pricing, coverage, compliance, workflows
- [OKF bundle tarball](${TARBALL_URL}): downloadable archive of the full bundle
- [Rate Index](${BUNDLE_URL}/rate-index.md): citable measured benchmark of all-inclusive W-2 hourly rates by role and tier
- [Staffing roles](${BUNDLE_URL}/roles/index.md): the ${roles.roles.length} roles with skill tiers and rate bands
- [Rate card](${BUNDLE_URL}/pricing/rate-matrix.md): published per-role rates by market tier
- [Market coverage](${BUNDLE_URL}/cities/index.md): the ${cities.cities.length} markets, by tier
- [State compliance](${BUNDLE_URL}/compliance/index.md): minimum wage and overtime for all 51 US jurisdictions
- [Workflows](${BUNDLE_URL}/workflows/index.md): plan staffing, ordering, compliance, request a quote

## Live tools (action layer)
- [MCP server](${MCP_ENDPOINT}): Streamable HTTP, no auth, ${TOOLS.map((t) => t.name).join(", ")}
- [REST API](${API_BASE}): HTTP mirror of the same query layer (OpenAPI 3.1 at ${OPENAPI_URL})
- [MCP discovery](https://mcp.tempguru.co/.well-known/mcp.json) · [OKF discovery](https://mcp.tempguru.co/.well-known/okf.json)

## Contact
- [Get staffing](${SITE}/get-staffing)
- [AI / developer docs](${SITE}/ai)
- Email: megan@tempguru.co · Phone: (904) 206-8953
`;
writeFileSync(join(publicDir, "llms.txt"), llmsTxt);

// ── discovery doc + downloadable tarball ─────────────────────────────────────
// OKF v0.1 mandates no discovery doc; this is our convention, linked from
// llms.txt and the import guide. Lives beside the existing .well-known/mcp.json.
const okfDiscovery = {
  okf_version: OKF_VERSION,
  name: "TempGuru Event Staffing Knowledge",
  description: `Canonical OKF v0.1 knowledge bundle for hiring W-2 event staff across ${cities.cities.length} US and Canada markets.`,
  publisher: PUBLISHER,
  domain: "event-staffing-us-canada",
  canonical_site: SITE,
  bundle: { root: `${BUNDLE_URL}/`, index: `${BUNDLE_URL}/index.md`, tarball: TARBALL_URL },
  action_layer: { mcp: MCP_ENDPOINT, rest: API_BASE, openapi: OPENAPI_URL },
  tools: TOOLS.map((t) => t.name),
  updated: DATA_DATE,
};
mkdirSync(join(publicDir, ".well-known"), { recursive: true });
writeFileSync(join(publicDir, ".well-known", "okf.json"), JSON.stringify(okfDiscovery, null, 2) + "\n");

let tarballNote = "skipped (tar unavailable)";
try {
  execSync(`tar -czf "${join(publicDir, "okf.tar.gz")}" -C "${publicDir}" okf`, { stdio: "ignore" });
  tarballNote = "public/okf.tar.gz";
} catch {
  /* tar not present, git-clone remains the distribution path */
}

console.log(`Wrote ${fileCount} OKF files to ${outDir}`);
console.log(`Wrote public/llms.txt, public/.well-known/okf.json, ${tarballNote}`);
console.log(`  data v${cities._meta.version} (${DATA_DATE}) · ${cities.cities.length} markets · ${measuredTotal} measured · 51 states · ${roles.roles.length} roles · ${TOOLS.length} tools · ${API_OPS.filter((o) => o.path !== "/api/v1/health").length} endpoints`);
