// TempGuru MCP, static data loaders.
//
// All TempGuru MCP tools serve curated static data. The source JSON lives in
// content/mcp-data/ and is loaded at module init. No database, no per-request
// I/O, the whole tool tree is in-memory after first import.
//
// Data is regenerated by hand (or by a future build script) when the city
// footprint, rate floors, or compliance baselines change. This file is the
// single import point so future swaps to a DB-backed source touch one place.

import citiesData from "../../../content/mcp-data/cities.json";
import rolesData from "../../../content/mcp-data/roles.json";
import pricingData from "../../../content/mcp-data/role-pricing.json";
import stateData from "../../../content/mcp-data/state-compliance.json";

// ─── Types ────────────────────────────────────────────────────────────────

export type CityTier = "hub" | "mid" | "small";

export type City = {
  slug: string;
  name: string;
  state: string;
  state_abbr: string;
  country: string;
  tier: CityTier;
};

export type Role = {
  slug: string;
  name: string;
  description: string;
  skill_tier: number;
  typical_shift_length_hours: number;
};

export type PriceBand = { low: number; high: number };
export type RolePricing = { small: PriceBand; mid: PriceBand; hub: PriceBand };

export type StateCompliance = {
  name: string;
  min_wage: number;
  overtime_weekly: number;
  overtime_daily: number | null;
  unique_rules: string[];
};

// ─── Loaders (validated, exported) ────────────────────────────────────────

export const CITIES: City[] = (citiesData.cities as City[]).slice();

export const ROLES: Role[] = (rolesData.roles as Role[]).slice();

export const PRICING: Record<string, RolePricing> = pricingData.pricing as Record<
  string,
  RolePricing
>;

export const PRICING_META = pricingData._meta as {
  version: string;
  updated: string;
  notes: string;
  currency_default: string;
  tier_definitions: Record<CityTier, string>;
};

export const STATES: Record<string, StateCompliance> = stateData.states as Record<
  string,
  StateCompliance
>;

export const STATE_META = stateData._meta as {
  version: string;
  updated: string;
  notes: string;
  citation_note: string;
};

// ─── Lookups ──────────────────────────────────────────────────────────────

const CITY_BY_SLUG = new Map(CITIES.map((c) => [c.slug.toLowerCase(), c]));
const CITY_BY_NAME = new Map(CITIES.map((c) => [c.name.toLowerCase(), c]));

const ROLE_BY_SLUG = new Map(ROLES.map((r) => [r.slug.toLowerCase(), r]));
const ROLE_BY_NAME = new Map(ROLES.map((r) => [r.name.toLowerCase(), r]));

/** Find a city by slug, name, or "name, state" patterns. Returns null if not found. */
export function findCity(query: string): City | null {
  if (!query) return null;
  const q = query.trim().toLowerCase();
  // Try slug exact match
  const bySlug = CITY_BY_SLUG.get(q);
  if (bySlug) return bySlug;
  // Try slug with -event-staffing suffix
  const bySlugWithSuffix = CITY_BY_SLUG.get(`${q}-event-staffing`);
  if (bySlugWithSuffix) return bySlugWithSuffix;
  // Try city name only
  const byName = CITY_BY_NAME.get(q);
  if (byName) return byName;
  // Try "name, state" or "name state", take everything before the first comma or last space
  const commaIdx = q.indexOf(",");
  if (commaIdx > 0) {
    const cityPart = q.slice(0, commaIdx).trim();
    const byPart = CITY_BY_NAME.get(cityPart);
    if (byPart) return byPart;
  }
  return null;
}

/** Find a role by slug or name. Returns null if not found. */
export function findRole(query: string): Role | null {
  if (!query) return null;
  const q = query.trim().toLowerCase();
  return ROLE_BY_SLUG.get(q) ?? ROLE_BY_NAME.get(q) ?? null;
}

/** Look up state compliance by 2-letter abbreviation OR full state name. */
export function findState(query: string): { abbr: string; data: StateCompliance } | null {
  if (!query) return null;
  const q = query.trim();
  // Try abbreviation
  const upper = q.toUpperCase();
  if (STATES[upper]) return { abbr: upper, data: STATES[upper] };
  // Try full name match
  const lowerQ = q.toLowerCase();
  for (const [abbr, data] of Object.entries(STATES)) {
    if (data.name.toLowerCase() === lowerQ) {
      return { abbr, data };
    }
  }
  return null;
}
